[package]
name = "www2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["macros"] }
chrono = "0.4.31"
maud = { version = "0.25.0", features = ["axum"] }
reqwest = "0.11.23"
tokio = { version = "1.35.1", features = ["full"] }
